[package]
name = "local_area_sort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
image = "0.24.6"
macroquad = "0.3.25"
itertools = "0.11.0"
colors-transform = "0.2.11"